### PR TITLE
Promise error

### PR DESCRIPTION
**Pull request by LoicMahieu**
Hi
This PR update all dependencies. I wasn't able to run tests without that.
Fix tests due to `undefined` did not end the stream
And finally the stream will now emit the error of the promise

### CODE REVIEW

**Comment by schnittstabil** [comment]
Thanks for contributing @LoicMahieu!

**Comment by LoicMahieu** [comment]
Thanks @schnittstabil 
Could you please publish a new version on npm :D ?

**Comment by schnittstabil** [comment]
@LoicMahieu I've dropped the whole `new Error('rejected')` part, see: https://github.com/schnittstabil/stream-from-promise/commit/46abb41e94f0c41a57176be62665b44acddc6d75

**Comment by schnittstabil** [comment]
@LoicMahieu [v1.0.0](https://github.com/schnittstabil/stream-from-promise/releases/tag/v1.0.0) is published :tada:

**Pull request closed without merging**
